version: '3.9'
services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DOCKER_BUILDKIT: 1

        deploy:
            resources:
                limits:
                    memory: 4096M
                reservations:
                    memory: 2048M
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        depends_on:
            database: 
                condition: service_healthy

    database:
        container_name: db
        image: mysql:8.0.37
        restart: unless-stopped
        command:
            [
                '--default-authentication-plugin=caching_sha2_password',
                '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            ]
        ports:
            - '${DATABASE_EXTERNAL_PORT}:3306'
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: ${DATABASE_NAME}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            start_period: 5s
            interval: 5s
            timeout: 10s
            retries: 10

volumes:
    db_data:
